import { 
  Home, 
  Camera, 
  Video, 
  Upload, 
  User, 
  Layers, 
  Lock, 
  KeyRound, 
  Plus, 
  Trash2, 
  ArrowLeft, 
  ArrowRight, 
  Save, 
  Search, 
  Filter, 
  Lightbulb, 
  Moon, 
  RefreshCw, 
  Settings, 
  FileText, 
  Bot, 
  ChevronDown, 
  ChevronUp, 
  ArrowDown, 
  ArrowUp, 
  Eye, 
  RotateCcw, 
  Check, 
  XCircle, 
  X, 
  Scaling, 
  Sliders, 
  Globe, 
  RotateCw, 
  Database, 
  ChevronLeftCircle, 
  ChevronRightCircle, 
  MoreVertical, 
  Edit3, 
  Info, 
  Crop,
  Gamepad2,
  Film,
  ClipboardList,
  LayoutList,
  Workflow
} from 'lucide-react';

export {
  Home as HomeIcon,
  Camera as CamerasIcon,
  Video as VideosIcon,
  Upload as UploadIcon,
  User as UserIcon,
  Layers as PhantomsIcon,
  Lock as RolesIcon,
  KeyRound as AuthIcon,
  Plus as AddIcon,
  Trash2 as DeleteIcon,
  ArrowLeft as BackIcon,
  Save as SaveIcon,
  Search as SearchIcon,
  Filter as FilterIcon,
  Lightbulb as LightModeIcon,
  Moon as DarkModeIcon,
  RefreshCw as RefreshIcon,
  Settings as SettingsIcon,
  FileText as DocumentationIcon,
  Bot as RobotArmIcon,
  ChevronDown as NextIcon,
  ChevronUp as PreviousIcon,
  ArrowDown as DownIcon,
  ArrowUp as UpIcon,
  Eye as PreviewIcon,
  RotateCcw as RestartIcon,
  Check as CheckIcon,
  XCircle as CancelIcon,
  X as CloseIcon,
  Scaling as CalibrateIcon,
  Sliders as AdjustIcon,
  Globe as LanguageIcon,
  RotateCw as RevertIcon,
  Database as DatabaseIcon,
  ChevronLeftCircle as ArrowLeftIcon,
  ChevronRightCircle as ArrowRightIcon,
  MoreVertical as DotsVerticalIcon,
  Edit3 as PencilIcon,
  Info as InfoIcon,
  Crop as CropIcon,
  Gamepad2 as ControlsIcon,
  Film as StreamsIcon,
  LayoutList as JobsIcon,
  Workflow as WorkflowIcon
};
