"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { useState } from "react";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

// Dynamically import Sidebar and ThemeProvider components
const Sidebar = dynamic(() => import("@/components/sidebar"), { ssr: false });
const ThemeProvider = dynamic(() => import("@/components/provider/themeProvider/ThemeProvider").then((mod) => mod.ThemeProvider), { ssr: false });

// Uncomment this if you need metadata
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isCollapsed, setIsCollapsed] = useState(true);

  const toggleSidebar = () => {
    setIsCollapsed(!isCollapsed);
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Add any head tags here */}
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex h-screen w-full bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100">
            <Sidebar isCollapsed={isCollapsed} toggleSidebar={toggleSidebar} />
            <div
              className={`flex flex-col w-full h-full transition-all duration-300 ${isCollapsed ? "ml-20" : "ml-64"
                } p-4`}
            >
              {children}
            </div>
            <Toaster />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
