"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// Uncomment this if you need metadata
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isCollapsed, setIsCollapsed] = useState(false);

  const toggleSidebar = () => {
    setIsCollapsed(!isCollapsed);
  };

  return (
    <html lang="en">
      <head>
        {/* Add any head tags here */}
      </head>
      <body className={inter.className}>
        <div className="flex h-screen w-full bg-gray-100">
          <Sidebar isCollapsed={isCollapsed} toggleSidebar={toggleSidebar} />
          <div
            className={`flex flex-col w-full h-full transition-all duration-300 ${
              isCollapsed ? "ml-20" : "ml-64"
            } p-4`}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
